name: stun_dart
version: 0.1.0+1-dev
author: "Ronit Ramdam BK <ron.ram5126@gmail.com>"
homepage: https://github.com/ronram5126/stun-dart
description: Simple plug and play stun client for dart. This will let you know your current public IP, port and NAT type details.

environment:
  sdk: ">=2.2.2"

dependencies:
  uuid: ^2.0.4
  dart_stringprep: ^0.1.0+4-dev

dev_dependencies:
  test: ^1.3.0